// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultPageContainer: typeof import('./src/components/DefaultPageContainer.tsx')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    HeaderRight: typeof import("./src/components/DefaultLayout/HeaderRight.tsx")["default"]
    Layout: typeof import("./src/components/DefaultLayout/Layout.tsx")["default"]
    NavigationTab: typeof import("./src/components/DefaultLayout/NavigationTab/NavigationTab.tsx")["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabItem: typeof import("./src/components/DefaultLayout/NavigationTab/TabItem.tsx")["default"]
  }
}
